# Generated by Django 4.1.2 on 2022-10-23 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="media",
            old_name="image",
            new_name="img_url",
        ),
    ]
