# Generated by Django 4.1.2 on 2022-10-27 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "product category",
                "verbose_name_plural": "product categories",
            },
        ),
        migrations.AlterField(
            model_name="media",
            name="product_inventory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="media",
                to="inventory.productinventory",
            ),
        ),
    ]
