

version: "3.8"

services:
  pgdb:
    profiles: [ "dev" ]
    container_name: pgdb_101_ecommerce
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db_101_ecommerce
      - POSTGRES_USER=101ecommerceuser
      - POSTGRES_PASSWORD=mypass


  elasticsearch:
    container_name: search
    image: elasticsearch:7.16.2
    environment:
      - cluster.name=ecommerce-elasticsearch
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    depends_on:
      - pgdb