

version: "3.8"

services:
  pgdb:
    container_name: pgdb_101_ecommerce
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db_101_ecommerce
      - POSTGRES_USER=101ecommerceuser
      - POSTGRES_PASSWORD=mypass


  esearch:
    container_name: search
    image: elasticsearch:7.14.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"